= Cardinal Collections for PHP

image:https://github.com/vrza/cardinal-collections/actions/workflows/build.yml/badge.svg[Build Status (GitHub Actions),link=https://github.com/vrza/cardinal-collections/actions]

A toolkit for building custom PHP collections.

Included are:

- two fast and reusable generic iterator implementations in pure PHP

- implementations of mutable Map and Set, but with anything as key

- utilities for working with iterables

- utilities for hashing arrays and objects

== Map and Set features

Reduce, map and filter:

[source,php]
----
$set = new Set([1, 3, 5, 7]);
$sum = $set->reduce(function ($acc, $x) {
    return $acc + $x;
});
echo $sum;
// output: 16
----

[source,php]
----
$set = new Set([0, 1, 2, 3]);
$squares = $set->map(function ($x) {
    return $x * $x;
});
echo $squares;
// output: { 0, 1, 4, 9 }
----

[source,php]
----
$set = new Set([0, 1, 2, 3, 4, 5, 6, 7]);
$odd = $set->filter(function($x) {
    return $x % 2 == 1;
});
echo $odd;
// output: { 1, 3, 5, 7 }
----

Collections implement `ArrayAccess`, `Iterator` and `Countable` interfaces, so in many ways you can work with them like you work with standard PHP arrays:

[source,php]
----
$map[] = ['foo' => 'bar'];
$value = $map[0];
unset($map[0]);
count($map);
foreach ($map as $key => $value);
----

Mutations while iterating mostly work as expected:

[source,php]
----
$set = new Set([ 1, 2, 3 ]);
$previous = false;
foreach ($set as $elem) {
    if ($previous) $set->remove($previous);
    $previous = $elem;
}
echo $set;
// output: { 3 }
----

== API Reference

=== Map

==== Constructor
[source,php]
----
Map(iterable $iterable = [])
----
Creates a new Map, initialized using keys and values from the given iterable. If called without arguments, an empty Map is created.

==== put
[source,php]
----
put($key, $value): Map
----
Adds an element to the Map. Returns the Map with the added element.

==== add
[source,php]
----
add($key, $value): Map
----
An alias for `put`.

==== putIfAbsent
[source,php]
----
putIfAbsent($key, $value)
----
If the key is not in the Map, adds a new key/value pair, returning null. If the key is present in the Map, returns the existing value.

==== append
[source,php]
----
append($value): Map
----
Appends a value to the Map, using the next available numeric key. Returns the Map.

==== remove
[source,php]
----
remove($key): Map
----
Removes a key from the Map, returning the Map.

==== delete
[source,php]
----
delete($key): Map
----
An alias for `remove`.

==== get
[source,php]
----
get($key, $default = null)
----
Returns the value associated with the key, or `$default` value if the key is not present in the Map.

==== count
[source,php]
----
count(): int
----
Returns the number of elements in the Map.

==== isEmpty
[source,php]
----
isEmpty(): bool
----
Returns true if the Map is empty.

==== nonEmpty
[source,php]
----
nonEmpty(): bool
----
Returns true if the Map contains at least one element.

=== Set
[source,php]
----
Set(iterable $iterable = [])
----
Creates a new Set, initialized using values of the given iterable. If called without arguments, an empty Set is created.

==== add
[source,php]
----
add($element): Set
----
Adds an element to the Set. Returns the Set with added element.

==== has
[source,php]
----
has($element): bool
----
Returns true if the element is a member of the Set.

==== contains
[source,php]
----
contains($element): bool
----
An alias for `has`.

==== remove
[source,php]
----
remove($element): Set
----
Removes an element from the Set, returning the Set without the element.

==== delete
[source,php]
----
delete($key): Set
----
An alias for `remove`.

==== equals
[source,php]
----
equals(Set $otherSet): bool
----
Returns true if Set and `$otherSet` are equal.

==== subsetOf
[source,php]
----
subsetOf(Set $otherSet): bool
----
Returns true if Set is a subset of `$otherSet`.

==== union
[source,php]
----
union(Set $otherSet): Set
----
Returns the union of Set and `$otherSet`.

==== intersect
[source,php]
----
intersect(Set $otherSet): Set
----
Returns the intersection of Set and `$otherSet`.

==== difference
[source,php]
----
difference(Set $otherSet): Set
----
Returns a new Set with all members of Set that are not members of `$otherSet`.

==== count
[source,php]
----
count(): int
----
Returns the number of elements in the Set.

==== isEmpty
[source,php]
----
isEmpty(): bool
----
Returns true if the Set is empty.

==== nonEmpty
[source,php]
----
nonEmpty(): bool
----
Returns true if the Set contains at least one element.

== Setup

Add the following to your `composer.json`:

[source,json]
----
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/vrza/cardinal-collections"
         }
    ],
    "require": {
        "vrza/cardinal-collections": "dev-main"
    }
}
----
