name: build

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.1', '8.0', '7.4', '7.3']
        phpunit-versions: ['^9']
        include:
        - operating-system: 'ubuntu-latest'
          php-versions: '7.2'
          phpunit-versions: '^8'
        - operating-system: 'ubuntu-latest'
          php-versions: '7.1'
          phpunit-versions: '^7'

    runs-on: ${{ matrix.operating-system }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        ini-values: xdebug.mode=coverage
        coverage: xdebug
        tools: phpunit:${{ matrix.phpunit-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit --colors=always --whitelist src --coverage-text tests
